#!/bin/bash

# Determine the operating system, in a horrible way...
if [ -f /etc/debian_version ]
then
  echo 'Detected a debian-based operating system'

  # Update package list
  apt-get update

elif [ -f /etc/redhat-release ]
then
  echo 'Detected a redhat-based operating system'
else
  echo 'Cannot detect operating system :('
  exit 1
fi
