#!/bin/bash

# Determine the operating system, in a horrible way...
if [ -f /etc/debian_version ]
then
  echo 'Detected a debian-based operating system'

  # Install puppet apt repository and gpgkey
  wget http://apt.puppetlabs.com/puppetlabs-release-precise.deb
  sudo dpkg -i puppetlabs-release-precise.deb
  rm puppetlabs-release-precise.deb

  # Update and install puppet
  sudo apt-get update
  sudo apt-get install puppet -y --assume-yes

elif [ -f /etc/redhat-release ]
then
  echo 'Detected a redhat-based operating system'
else
  echo 'Cannot detect operating system :('
  exit 1
fi
