#!/bin/bash

set -e

# This script sets up a Ubuntu server as a puppet-master
# It installs and configures the following packages:
#  -  puppet-dashboard
#  -  puppet-master
#  -  puppetDB
# libnet-ldap-perl, which is used for the canonical config generation, is also installed

# This function set uncomments and sets the value for keys in a configuration file
function set_key_value
{
  file=$1
  key=$2
  delimiter=$3
  value=$4
  sudo sed --in-place='' --expression="s/^[[:space:]]*#*[[:space:]]*$key[[:space:]]*$delimiter.*\$/$key$delimiter$value/g" $file
}

# Ensure user is root
LUID=$(id -u)
if [[ $LUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

DOMAIN=`cat /etc/resolv.conf  | grep search | awk '{ print $2 }'`

# Install puppet apt repository and gpgkey
wget http://apt.puppetlabs.com/puppetlabs-release-precise.deb
sudo dpkg -i puppetlabs-release-precise.deb
rm puppetlabs-release-precise.deb
sudo apt-get update

# Create required variables and set as lowercase, as this is needed for puppet-dashboard certificates
LCASE_HOSTNAME=${HOSTNAME,,}

# Install ruby pre-requisites for puppet-dashboard
sudo apt-get install -y build-essential irb libmysql-ruby libmysqlclient-dev \
  libopenssl-ruby libreadline-ruby rake rdoc \
  ri ruby ruby-dev

# Installs the correct version of rubygems, needed for puppet-dashboard
(
 URL="http://production.cf.rubygems.org/rubygems/rubygems-1.3.7.tgz"
 PACKAGE=$(echo $URL | sed "s/\.[^\.]*$//; s/^.*\///")

 cd $(mktemp -d /tmp/install_rubygems.XXXXXXXXXX) && \
 wget -c -t10 -T20 -q $URL && \
 tar xfz $PACKAGE.tgz && \
 cd $PACKAGE && \
 sudo sudo ruby setup.rb
)

# Install packages and depencies
sudo apt-get install -y puppetmaster puppet-common puppetdb puppetdb-terminus

# Stop puppetmaster and Move puppet configuration directory
# and checkout the puppet configuration from company-servers
sudo /etc/init.d/puppetmaster stop
sudo mv /etc/puppet /etc/puppet.bak
ls -ls /vagrant
sudo cp -r /vagrant/puppet /etc/puppet

# Configure puppet-master
set_key_value '/etc/puppet/puppet.conf' 'dns_alt_names' ' = ' "puppet-master,puppet-master.$DOMAIN,$LCASE_HOSTNAME,$LCASE_HOSTNAME.$DOMAIN"
set_key_value '/etc/default/puppetmaster' 'start' '=' 'yes'
sudo /etc/init.d/puppetmaster start

# Configure puppet DB
set_key_value '/etc/puppet/puppetdb.conf' 'server' ' = ' "$LCASE_HOSTNAME.$DOMAIN"

# Restart puppetdb and puppet-master
sudo /etc/init.d/puppetdb restart
sudo /etc/init.d/puppetmaster restart

echo "The installation is complete."
